# Generated by Django 3.2.20 on 2023-09-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('completedBy', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('issuer', models.CharField(max_length=255)),
                ('isPaid', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
